### PR TITLE
Issue #655 - Added check to remove trailing forward slash if found in…

### PR DESCRIPTION
**Pull request by kobrien**
… proxy URL

### CODE REVIEW

**Comment by rokikon** [comment]
@tomakehurst Hi! Could you please review this PR, because I've met this kind of issue few times. Thanks.

**Comment by tomakehurst** [comment]
I'm planning to review it, just haven't had time yet.

**Comment by rokikon** [comment]
@tomakehurst is it possible that this one will be included into the next release version?

**Comment by tomakehurst** [comment]
It's certainly possible

**Pull request merged**
