### PR TITLE
When running the build from command line (not IntelliJ) it was failin…

### PR DESCRIPTION
**Pull request by wojciechbulaty**
…g complaining it has found 4 not 1 near misses in successfullyCalculatesNearMissesWhenACustomMatcherIsRegistered

### CODE REVIEW

**Comment by wojciechbulaty** [comment]
[log_after_fix.txt](https://github.com/tomakehurst/wiremock/files/628498/log_after_fix.txt)
[log_before_fix.txt](https://github.com/tomakehurst/wiremock/files/628497/log_before_fix.txt)

**Comment by wojciechbulaty** [comment]
Tom, could we merge this guy, please?

**Comment by tomakehurst** [comment]
I have a fix I'd prefer to apply in my workspace. I'll push it shortly.

**Comment by wojciechbulaty** [comment]
Got it. No worries.

**Pull request closed without merging**
