### PR TITLE
Added ability to match requests relationally (e.g. more than/less than 5 requests)

### PR DESCRIPTION
**Pull request by sampengilly**
Correct base branch this time.

Added a new overload of verify() that takes a CountMatchingStrategy as it's first argument. This strategy can be obtained via static convenience methods to create the following assertions:

* `verify(moreThan(5), getRequestedFor(...))`
* `verify(moreThanOrExactly(5), getRequestedFor(...))`
* `verify(exactly(5), getRequestedFor(...))`
* `verify(lessThanOrExactly(5), getRequestedFor(...))`
* `verify(lessThan(5), getRequestedFor(...))`

### CODE REVIEW

**Comment by sampengilly** [comment]
Merged 2.0-beta into my master to fix conflicts

**Comment by tomakehurst** [comment]
Hi, apologies for the delay in reviewing this.

This is failing to compile with JDK 7 due to the use of ``BiPredicate``. Although we toyed with the idea of dropping Java 7 support in 2.0, a few folks spoke up against it so we're keeping it for a while longer.

**Comment by sampengilly** [comment]
Fair enough, I hadn't seen the update. All that's required is for me to undo the last commit, I'll push that shortly.

**Comment by tomakehurst** [comment]
Merged info 2.0-beta with rebase

**Pull request closed without merging**
