### PR TITLE
[Bala] Typo & formatting fix in documentation

### PR DESCRIPTION
**Pull request by balajeetm**
As I was reading the documentation, I saw a few typos. Thought I would fix it myself. Thanks for the great tool.

### CODE REVIEW

**Comment by tomakehurst** [comment]
Hi,

I really appreciate you taking the time to help with this. Unfortunately the `gh-pages` branch is generated automatically from the Jekyll project under `docs-v2`.

Would you be willing to raise a PR to fix these in the source markdown?

Thanks,
Tom

**Comment by balajeetm** [comment]
Sure, I will do the needful. I did run the jekyll server locally but I wasn't able to find the the source. I'll make changes to doc-v2 and submit the PR. How is the generated code moved to gh-pages?

**Comment by balajeetm** [comment]
Why I ask is, once I generate the files locally by running jekyll and feel the changes the as per expectations, I can raise the PR for master. Do you manually push the generated site to gh-pages?

**Comment by tomakehurst** [comment]
I have a script (`gen-docs.sh`) that builds the Jekyll project, copies the resulting files into the gh-pages branch and pushes.

**Comment by balajeetm** [comment]
Great, thanks will raise another PR

**Pull request closed without merging**
