### PR TITLE
Add user authentication for the Proxy via

### PR DESCRIPTION
**Pull request by kevinrigot**
Hi,
I added the support of proxy-via that needs a proxy with authentication.
ie: http://user:password@proxy.com

PS: I had 2 broken UT related to internationalization:
    Expected: is "Content is not allowed in prolog.; line 1; column 1"
         but: was "Contenu non autorisé dans le prologue.; line 1; column 1"

com.github.tomakehurst.wiremock.matching.EqualToXmlPatternTest > logsASensibleErrorMessageWhenActualXmlIsBadlyFormed FAILED

com.github.tomakehurst.wiremock.AdminApiTest > returnsBadEntityStatusWhenInvalidEqualToXmlSpecified FAILED

Kevin

### CODE REVIEW

**Comment by tomakehurst** [comment]
Thanks for this. Sorry it's taken so long to merge!

**Comment by mikehenry-se** [comment]
Please update documentation on this so we don't need to sift through old PRs to find it. thx

**Comment by tomakehurst** [comment]
I'm always happy to accept documentation improvement PRs @mikehenry-se

**Comment by mikehenry-se** [comment]
Done! #1294

**Pull request merged**
