### PR TITLE
Add PUSH and PURGE HTTP method constants

### PR DESCRIPTION
**Pull request by dtanner**
Apache Traffic Server and some other cache servers use the PUSH and PURGE methods.

### CODE REVIEW

**Comment by tomakehurst** [comment]
Are you aware that you can new up ``RequestMethod`` with any verb you want?

**Comment by dtanner** [comment]
Yeah - here's what I'm currently doing in the tests:
`stubFor(new BasicMappingBuilder(new RequestMethod("PURGE"), urlEqualTo("/"))`
It's not a huge deal, but it feels a little dirty since I'm exceeding my access rights to the BasicMappingBuilder constructor (I'm using Groovy).  I was hoping to use a more concise helper method like:
`stubFor(purge("/"))`  

But it's not the end of the world either way - my tests are working great, so a big huge thanks for building the tool.  It doesn't look like those methods are in the spec, so I understand if you don't want to add them.  I just realized my PR didn't add that helper method.  Let me know what you think, and if you do want to add them, let me know if there are other places I should check to add.

**Comment by dtanner** [comment]
p.s. And maybe I missed an available method that isn't package private, to avoid the exceeded access.?

**Comment by tomakehurst** [comment]
The DSL makes non-standard methods available like this:

```java
stubFor(request("PURGE", urlEqualTo("/purge/this"))
```

I'm a bit reluctant to start adding more (less/non standard) verbs. To be consistent with the rest it'd also be necessary to add extra DSL methods and a few other bits here and there. What I'm trying to avoid is adding maintenance overhead for niche cases that are achievable via some other route.

**Comment by dtanner** [comment]
Sure - I understand.  Thanks for the usage tip - I'll switch to that.

**Comment by tomakehurst** [comment]
No probs

**Pull request closed without merging**
