### PR TITLE
Feature/near miss via junit rule

### PR DESCRIPTION
**Pull request by reftel**

### CODE REVIEW

**Comment by tomakehurst** [comment]
Thanks for submitting this. Quick question - why split the tests over so many classes? I can see that you might want one for ClassRule and one for Rule, but beyond that I'm not sure I understand the value.

**Comment by magnusr** [comment]
Well, `WireMockClassRule` should get to do its thing before and after each test, so each test for `WireMockClassRule` needs be a separate class, right?
But anyway, they don't, need to be separate source files. Fixed that, and rebased to master.

**Comment by reftel** [comment]
@tomakehurst : Anything left to improve in this PR, or can it be merged?

**Comment by tomakehurst** [comment]
Apologies for not merging yet. I wanted to review the tests a little more as I think there might be some duplication. It's on my list!

**Pull request merged**
