### PR TITLE
Admin: Docs: Add delete request by ID to swagger docs

### PR DESCRIPTION
**Pull request by DrMattFaulkner**

### CODE REVIEW

**Comment by tomakehurst** [comment]
Thanks for working on this.

Couple of things:
* `/requests/remove` and `/requests/remove-by-metadata` both return full lists of the requests removed rather than a count.
* Please could you also add the remove by ID resource (`DELETE /requests/{id}`)?

**Comment by DrMattFaulkner** [comment]
1. Fixed
2. `/__admin/requests/{requestId}` is already there.

**Comment by DrMattFaulkner** [comment]
@tomakehurst Is this good to go?

**Comment by tomakehurst** [comment]
Thanks!

**Pull request merged**
