### PR TITLE
Isolate jetty dependencies into a single package

### PR DESCRIPTION
**Pull request by dsyer**
The servlet and request adapters have moved to the "servlet" package.
The only dependency they had on jetty was conditional anyway, so
the condition was also modified to not even require jetty on the
classpath.

See gh-407. Not a complete modularization yet, but splits up the
servlet-only stuff from the jetty server.

### CODE REVIEW

**Comment by tomakehurst** [comment]
I think it might be necessary to split out the code that builds the fault injector from ``WireMockHandlerDispatchingServlet`` as at the moment it still indirectly references Jetty classes, so I think it's unlikely to run if Jetty is taken off the classpath.

**Comment by dsyer** [comment]
Interestingly it does work fine, at least for simple use cases without faults I guess. I added an extra abstraction to fix the problem in general (see last commit).

**Comment by tomakehurst** [comment]
I've merged this onto a branch and changed a few bits as I discovered that it'll throw an NPE if there's no fault injector specified. There are also a couple of tests for an alternative HTTP server. See what you think:

https://github.com/tomakehurst/wiremock/tree/dsyer-feature/jetty-isolation

**Comment by dsyer** [comment]
LGTM. Thanks.

**Pull request merged**
