### PR TITLE
Fix request model documentation in response-templating document

### PR DESCRIPTION
**Pull request by pmihalcin**
Remove .requestLine substring

### CODE REVIEW

**Comment by tomakehurst** [comment]
Not sure why you want to do this - the `requestLine` part is correct. Am I missing something?

**Comment by pmihalcin** [comment]
@tomakehurst when I was trying to use `requestLine`, it wasn't resolved correctly.

Simply put, 
just compare the `description` and `example` you have in doc:
`request.requestLine.query.<key>` vs `request.query.search` - there is no `requestLine` in the example

The same applies everywhere where `requestLine` is used.

**Comment by tomakehurst** [comment]
Are you on the latest version?

**Comment by pmihalcin** [comment]
I see.. how can I view documentation for `com.github.tomakehurst:wiremock:2.6.0`? sorry for the noise

**Comment by tomakehurst** [comment]
I'd strongly suggest upgrading to 2.20.0 if you can. It's fully backwards compatible.

However, if you absolutely can't, you can view the docs in GH by tag: https://github.com/tomakehurst/wiremock/blob/2.6.0/docs-v2/_docs/response-templating.md#the-request-model

**Comment by pmihalcin** [comment]
Thanks. I upgraded to the latest version. 
Now both `request.requestLine.query.goto` and also `request.query.goto` work

**Pull request closed without merging**
