### PR TITLE
#786 - asynchronous wiremock

### PR DESCRIPTION
**Pull request by jerzykrlk**
This one adds asynchronous servlet-api in Wiremock. I've assembled what I found here:
https://github.com/tomakehurst/wiremock/issues/786

... and here:
https://github.com/hmalewska/wiremock/pull/1

@tomakehurst could you have a look and tell what you think?

### CODE REVIEW

**Comment by adamgo** [comment]
Could you please merge this?

**Comment by tomakehurst** [comment]
I will when I get the chance. Chasing me about it isn't going to make my day job go away, sadly.

**Comment by jerzykrlk** [comment]
I'm sorry, we didn't mean to be pushy - I just got some support from the teammates.

Thanks and best regards,
Jerzy

**Comment by tomakehurst** [comment]
Sorry, one thing I forgot to ask for before releasing this - please could you document this in the `configuration` and `running-standalone` pages? I guess a new PR with this would be simplest.

Thanks.

**Comment by jerzykrlk** [comment]
Sure, I'll take care of it after Christmas.

Thank you.

**Comment by jerzykrlk** [comment]
Actually, it turned out to be less work that I thought. Here we go: https://github.com/tomakehurst/wiremock/pull/836

Best regards.

**Pull request merged**
