### PR TITLE
Bumping jackson-databind version to 2.9.9.3 to fix CVE's

### PR DESCRIPTION
**Pull request by kai-eckert**

### CODE REVIEW

**Comment by tomakehurst** [comment]
Please can you merge across from master, as this should fix the Travis build errors

**Comment by kai-eckert** [comment]
How can i doo that ?

**Comment by tomakehurst** [comment]
https://help.github.com/en/articles/merging-an-upstream-repository-into-your-fork

**Comment by tomakehurst** [comment]
Thanks

**Pull request merged**
