### PR TITLE
Add default request config check stale conn

### PR DESCRIPTION
**Pull request by Joe-Klauza**

### CODE REVIEW

**Comment by Joe-Klauza** [comment]
Solves Issue #620 , but it might cause some issues for others.

**Comment by tomakehurst** [comment]
Sorry for the delay in getting back to you. I'm fine with the actual code change, but the test case is a bit of a mess.

I get that this is tricky to test properly, but can you think of a way of putting a proper test for this into the suite?

**Comment by Joe-Klauza** [comment]
I agree the test case is a mess; sorry about that. Unfortunately we don't know of a way to reproduce this issue outside of Couchbase, so spinning up a local instance and performing the API calls are necessary steps to reproduce it. As such I'm not really sure how to simplify the test other than removing some of the extraneous logging or perhaps unused imports... I'm okay with removing the test entirely, but like I said I'm not sure if setting the stale connection check would cause issues for others.

**Comment by tomakehurst** [comment]
I can think of some ways it could be done but they're totally overkill. In this case I think just removing the exiting test and living without a proper one is OK.

**Comment by Joe-Klauza** [comment]
Should be all set, @tomakehurst. Thank you!

**Pull request merged**
