### PR TITLE
add verify with CountMatchingStrategy

### PR DESCRIPTION
**Pull request by lukasGemela**
resolves https://github.com/tomakehurst/wiremock/issues/1280

### CODE REVIEW

**Comment by tomakehurst** [comment]
Thanks for raising this. Please could you add an acceptance test case?

**Comment by lukasGemela** [comment]
Hi, yes sure. Sorry for delay got distracted by current events :)

**Comment by lukasGemela** [comment]
@tomakehurst can you please check the failing build? I made the test but test failing is completely unrelated to my changes, seems like everything is working fine locally and I cannot restart the pipeline due to missing restart button 🤔

**Comment by tomakehurst** [comment]
Thanks!

**Pull request merged**
