### PR TITLE
Add capability to set up a namespace context so that xpaths with namespa...

### PR DESCRIPTION
**Pull request by wdebeau1**
...ces can be supported without falling back on local-name()

### CODE REVIEW

**Comment by tomakehurst** [comment]
Please could you make a couple of changes:
1) Restore the indentation in the files changed in the first commit, as I'm having a hard time distinguishing the significantly changed lines from the reformatted ones, and
2) Remove the ``assertEquals`` call. A better solution would be to add a message to the ``assertThat`` call IMO.

**Comment by wdebeau1** [comment]
Sorry about the whitespace stuff, it should be fixed now.

As to the test...
I had changed the test to assertEquals to try to see what status code I was getting back, since assertThat doesn't tell me. I was never able to reproduce the failure locally, and the code I was working on shouldn't have had any impact on that test (StandaloneAcceptanceTest.matchesVeryLongHeader()). It was only failing in one of the 1.7 builds, and when I added the assertEquals, the test started passing, so I was never able to figure out why it was failing in the first place. 
In any case, it should be back to its original form and it passed this time.

**Comment by davidnewcomb** [comment]
Is it pulled in yet?

**Comment by tomakehurst** [comment]
Merged as a new commit. Thanks for this, and sorry for the wait!

**Pull request closed without merging**
