### PR TITLE
Switched base64 encoding to native Java library

### PR DESCRIPTION
**Pull request by marsbradley**
Better performing according to this: http://java-performance.info/base64-encoding-and-decoding-performance/

Been profiling stubs with base64 encoded JSON objects and base64->encoding/decoding is by far the hottest method.

### CODE REVIEW

**Comment by tomakehurst** [comment]
Would mind sharing your method for measuring this?

Also, it looks like you're using some Java 8+ APIs. Is there a way to improve this without breaking Java 7 compatibility?

**Comment by marsbradley** [comment]
Used JMC attached to a build of our stubbing framework to do flight recordings of around 20 minutes of typical load. Showed a high percentage (50%) of cycles spent in com.google.io.BaseEncoding. See image for more information.

AFAIK Java 8 is when base encoding was implemented natively...

However javax.xml.bind.DatatypeConverter has a very similar implementation (in terms of speed) and is available in Java 6/7. Could reimplement the PR using that library instead?

**Comment by tomakehurst** [comment]
So for the profile you've shown there, you were using stubs with base64 encoded response bodies?

And do you know if it's encoding/decoding or both that are the bottleneck?

Just wondering if it's running hot because WM in unnecessarily re-encoding/decoding stuff more than once.

If you can get a significant performance improvement with `javax.xml.bind.DatatypeConverter` and keep Java7 compatible, that would be awesome.

Thanks!

**Comment by marsbradley** [comment]
Yes.

Just looked at the flight recordings again, seems the encoding is roughly 2:1 compared to decoding in terms of % time spent.

Yes I believe that is a related issue; there does seem to be a fair amount of unnecessary encoding/decoding on top of Guava's implementation being slow. If you'll look back at the JMC trace, you'll see that the UTF-8 decoder is still being called frequently, which was certainly unexpected from our end.

If wiremock.http.body stored each response body in the format it was provided in, rather than always converting base64/string -> byte[] and then byte[] -> base64/string when it's needed again, it would reduce the overhead of all this encoding/decoding, no?

I will try and get a Java 7 fix for this slowness together soon. I think reducing the number of unnecessary encoding/decoding cycles would also have a big performance impact though.

**Comment by tomakehurst** [comment]
OK, that'd be great. I'll try and find time to look into why excessive encoding/decoding is happening, and whether it's possible to fix without breaking backwards compatibility.

**Comment by marsbradley** [comment]
Pushed a Java 7 compatible fix :).

**Comment by tomakehurst** [comment]
Awesome! How much of a dent did that make on the original performance?

**Comment by marsbradley** [comment]
A small batch of initial test runs showed a speed-up of roughly 1.6x with all bodies Base64 encoded. Base64 encoding/decoding now takes up ~20% of execution time.

Unfortunately it's again slower than just using non-encoded bodies, mainly due to the UTF-8 decoder still being called. Also note that these are very much initial results based off a very small sample size, so I would take them with a grain of salt. I will do more thorough testing once the excessing encoding/decoding has properly been looked into.

Cheers

**Comment by tomakehurst** [comment]
Great, thanks for letting me know. I'll merge this for now, and try to carve out some time to look at the problem more deeply.

**Comment by marsbradley** [comment]
Just to update you, now that I've run some longer/more realistic tests. As expected, initial results were a bit optimistic. Real-world speed-up is still around 1.2x-1.3x with Base64 encoded bodies though.

Before:
image

After:
image

Base encoding still takes up the lion's share of execution time (even using the java.xml library), but this is something that would be better solved through reducing excessive calls.

The time spent decoding has also increased relative to the time spent encoding (now they're roughly even, before far more time was spent encoding), which leads to the interesting possibility that java.xml is faster at encoding, but google.io is faster at decoding. I think the differences would be too small to warrant an investigation though.

**Comment by tomakehurst** [comment]
Thanks for posting this, that's very useful. I'm happy to take a 1.3x speedup!

**Pull request merged**
