### PR TITLE
EqualToJsonPattern simplified

### PR DESCRIPTION
**Pull request by lukas-krecan**

### CODE REVIEW

**Comment by tomakehurst** [comment]
Ah nice, this is a big improvement! This looks like it might be good enough to fully integrate and merge.

Thanks!

**Comment by tomakehurst** [comment]
One question - it seems like the conversions to/from `JsonNode` are using a conversion function that does a tree walk, rather than simply wrapping/unwrapping, which (although better than parsing) will presumably still have a performance penalty.

Am I interpreting that correctly, or is there a shortcut somewhere that prevents a full conversion from happening when the type is already correct?

**Comment by lukas-krecan** [comment]
Conversion from JsonNode can be done directly (currently is not, but it's a one-liner). The opposite direction will indeed require some tree walking. 

I prefer to pay a small performance penalty than to maintain universal JSON node abstraction.

**Comment by lukas-krecan** [comment]
https://github.com/lukas-krecan/JsonUnit/commit/caa3d3056a2f80254e12be0c7579fa5945181e1d

**Comment by tomakehurst** [comment]
Implemented in 7ead912283b9c89d010eaf523e877ff5a5a5a728. Thanks again @lukas-krecan!

**Pull request closed without merging**
