### PR TITLE
Use modified requests

### PR DESCRIPTION
**Pull request by jeremydyoung**
I'm submitting this pull request because if you use the extension StubRequestFilter to wrap a request which modifies the URL that will be proxied, the original url gets used for the proxy request.

This change allows for a particular stub to retain the existing functionality of proxying the unmodified request url, or to set the useModifiedRequest flag to true, where the wrapped request will be sent to the ResponseDefinition when rendering the response.  

An example config might contain:

```
{
  "priority": 1,
  "request": {
    "headers" : {
      "X-Destination-Service" : {
        "equalTo" : "foo"
      }
    }
  },
  "response": {
    "proxyBaseUrl" : "https://foo.service/",
    "useModifiedRequest": "true"
  }
}
```

or in a test:

```
        stubFor(
                get(urlMatching('/.*'))
                        .withHeader('X-Destination-Service', containing('foo'))
                        .atPriority(1)
                        .willReturn(aResponse().withStatus(200)
                                .proxiedFrom('https://foo.service')
                                .withModifiedRequests()
                        )
        )
```
The filter I used with this feature is: 

```
public class ServiceNameFilter extends StubRequestFilter {
    @Override
    public RequestFilterAction filter(Request request) {
        String service = "foo";
        Request wrappedRequest = RequestWrapper.create()
                .transformAbsoluteUrl(url -> url.replaceFirst("/" + service, ""))
                .addHeader("X-Destination-Service", service)
                .wrap(request);
        return RequestFilterAction.continueWith(wrappedRequest);
    }

    @Override
    public String getName() {
        return "service-name-filter";
    }
}
```

Where my ServiceNameFilter stripped foo off the front of the url such as https://wiremock.server/foo/status, to make it so I wanted https://foo.service/status as the proxied request.  The filter was also responsible for adding the header.  In our case the reason for this was to disambiguate between two services that had the same url patterns for their requests that we wanted to mock out or proxy on.

Without my changes to ResponseDefinition, the proxied request was https://foo.service/foo/status, even though the filter wrapped the request and made it return /status as the url.

I wanted to make tests that asserted this behavior, but it turns out it wasn't clear where those tests should reside.  I can come back and add tests if someone provides a little guidance on what would fit well with the project.  

The default behavior is intended to be unchanged with this feature.  If there are unintended consequences for this change, then there may need to be adjustments.

I wasn't able to find the code from https://github.com/tomakehurst/wiremock/issues/1147 or seem to make it work with 2.24.1

This feature request seems relevant:
https://github.com/tomakehurst/wiremock/issues/1154

I think this may be a solution to this Feature Request:
https://github.com/tomakehurst/wiremock/issues/745

It might be possible to make the filter configurable, but since the filters seem to only be global, that seems difficult.  I dug into the code a little looking for something like this, but I am not extremely familiar with the code base, so I couldn't find a clear strategy.

### CODE REVIEW

**Comment by kovaku** [comment]
I am facing with same issue, although I have implemented the aforementioned `StubRequestFilter` and added an as extension, it is not able to amend the request that is proxied to 3rd party service. It would be great to have this PR merged 👍

**Comment by DanielScholtz** [comment]
+1

**Comment by tomakehurst** [comment]
Sorry for the wait. I decided maintaining an option to keep the original behaviour was too complicated/confusing, so I've switched the behaviour to always use the wrapped request here: f9e64d249889fb346b57bb6ea693b9da7d32de10

**Comment by nituspl** [comment]
Hi, I cannot use this feature. I have wiremock 2.27.2 and when trying to run standalone wiremock I get this error:

```
Exception in thread "main" com.github.tomakehurst.wiremock.standalone.MappingFileException: Error loading file /home/nituspl/wiremock/./mappings/proxy.json:
Unrecognized field "useModifiedRequest" (class com.github.tomakehurst.wiremock.http.ResponseDefinition), not marked as ignorable
	at com.github.tomakehurst.wiremock.standalone.JsonFileMappingsSource.loadMappingsInto(JsonFileMappingsSource.java:121)
	at com.github.tomakehurst.wiremock.core.WireMockApp.loadMappingsUsing(WireMockApp.java:204)
	at com.github.tomakehurst.wiremock.core.WireMockApp.loadDefaultMappings(WireMockApp.java:200)
	at com.github.tomakehurst.wiremock.core.WireMockApp.<init>(WireMockApp.java:103)
	at com.github.tomakehurst.wiremock.WireMockServer.<init>(WireMockServer.java:73)
	at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.run(WireMockServerRunner.java:65)
	at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.main(WireMockServerRunner.java:134)

```

**Comment by andrake1982** [comment]
have an error(the same as above) in standalone 2.28 version on
POST .../__admin/mappings
`{
    "request": {
        "urlPattern": "/cds/.*",
        "method": "GET"
    },
    "response": {
        "proxyBaseUrl": "http:cds.cluster.local/cds.service",
        "transformers":["service-name-filter"],
        "useModifiedRequest": "true"
    }
}`

get error
`{
    "errors": [
        {
            "code": 10,
            "source": {
                "pointer": "/response/useModifiedRequest"
            },
            "title": "Error parsing JSON",
            "detail": "Unrecognized field \"useModifiedRequest\" (class com.github.tomakehurst.wiremock.http.ResponseDefinition), not marked as ignorable"
        }
    ]
}`

**Comment by jeremydyoung** [comment]
> 
> 
> have an error(the same as above) in standalone 2.28 version on
> POST .../__admin/mappings
> `{ "request": { "urlPattern": "/cds/.*", "method": "GET" }, "response": { "proxyBaseUrl": "http:cds.cluster.local/cds.service", "transformers":["service-name-filter"], "useModifiedRequest": "true" } }`
> 
> get error
> `{ "errors": [ { "code": 10, "source": { "pointer": "/response/useModifiedRequest" }, "title": "Error parsing JSON", "detail": "Unrecognized field \"useModifiedRequest\" (class com.github.tomakehurst.wiremock.http.ResponseDefinition), not marked as ignorable" } ] }`
> 
> Looks like this is just not implemented

useModifiedRequest was not implemented.  The concept of using the modified request was made default without a flag.

**Comment by andrake1982** [comment]
@jeremydyoung with your solution(with builtin ServiceNameFilter) we would got the solution for [#745](https://github.com/tomakehurst/wiremock/issues/745) "Need proxyUrlPrefixToRemove for proxy" even for standalone Wiremock mode. But with applied solution we don't got builtin tool for mock separated endpoints for different services.
So users to achieve this at standalone wiremock should pack transformer into war, and then run it with extension. It can be not so trivial if wiremock deploing via Helm chart in kubernetes cluster. 

@tomakehurst is this feature at roadmap of wiremock future? really usefull feature. Many users need this.

**Comment by tomakehurst** [comment]
@andrake1982 the feature you're referring to - do you mean #745?

**Comment by andrake1982** [comment]
@tomakehurst 

> @andrake1982 the feature you're referring to - do you mean #745?
Yes

**Pull request closed without merging**
