### PR TITLE
I have refactored out and made public the code to add proxy mapping s…

### PR DESCRIPTION
**Pull request by wojciechbulaty**
…o that if you would like to create a recorder programmatically in your test suite you can do it.

Let me know what you think.

### CODE REVIEW

**Comment by tomakehurst** [comment]
Have you had a look at https://github.com/tomakehurst/wiremock/issues/546 ?

Rather than adding lots of piecemeal additions to record/playback I'd like to write a new feature and solve the accumulated issues that have come up over time that way.

I haven't explicitly called out the ability to record/playback from within automated tests, so I'll add that to the spec. I believe Betamax has got the right kind of model here. Adding the other stuff listed in this issue should mean it'd be fairly easy to write a rule that behaves how Betamax's does i.e. switchable via runtime config between recording and playback.

**Comment by wojciechbulaty** [comment]
I understand, it does sound like a good strategic approach.

In the meantime, what do you think about having a workaround for today? This changeset is a very small refactor and would help me avoid copying and pasting code.

**Comment by tomakehurst** [comment]
I'm not sure I'm totally clear on how this would be used, and why it's a better approach than a shortcut in the DSL.

Could you elaborate a bit?

**Comment by wojciechbulaty** [comment]
Sure, maybe I overlooked something and this is not necessary.

When you say "a shortcut in the DSL", can you give an example?

I am trying to start up a recorder programmatically, so I am replicating what WireMockServerRunner is doing in the run method:
```java
if (options.recordMappingsEnabled()) {
        wireMockServer.enableRecordMappings(mappingsFileSource, filesFileSource);
}

if (options.specifiesProxyUrl()) {
	addProxyMapping(options.proxyUrl(), wireMockServer);
}
```

Based on the above example, what I have done in my code is:
```java
wireMockServer.enableRecordMappings(mappingsFileSource, filesFileSource);
wireMockServer.loadMappingsUsing(new AddProxyMapping(proxyUrl));
```

**Comment by tomakehurst** [comment]
I suppose I'd want to write something like:

```java
stubFor(proxyAllTo("http://my.target.com"));
```

Where `proxyAllTo` is a static method on `WireMock` that configures a `MappingBuilder`.

One advantage of this is it gives me a way to delete it when I'm finished e.g.

```java
StubMapping proxyMapping = stubFor(proxyAllTo("http://my.target.com"));

// Do things...

removeStub(proxyMapping);
```

**Comment by tomakehurst** [comment]
My solution is in the DSL now, so closing.

**Pull request closed without merging**
