### PR TITLE
added an endpoint to edit body files

### PR DESCRIPTION
**Pull request by wojciechbulaty**
Let me know what you think please.

I have not added any tests yet cos did not want to waste time if there is a better way of doing this.

### CODE REVIEW

**Comment by tomakehurst** [comment]
I think this would be a great thing to have.

A few things to think about:

* What if you're trying to overwrite an existing file?
* Might be handy to have list and delete calls too
* The file write operation should be via the `FileSource` rather than doing it directly in the route handler IMO.

**Comment by tomakehurst** [comment]
One further thought: how easy do you think it'd be to support multipart posts so that more than one file can be added at a time?

**Comment by wojciechbulaty** [comment]
> What if you're trying to overwrite an existing file?

Good point, will test it.

> Might be handy to have list and delete calls too

I might add it soon. Would it be OK to add it as a separate pull request?

> The file write operation should be via the FileSource rather than doing it directly in the route handler IMO.

Will do that.

> One further thought: how easy do you think it'd be to support multipart posts so that more than one file can be added at a time?

Yeah, that seems like a useful thing. I was hoping to keep this changeset minimal if possible. May be somebody else can pick it up?

**Comment by tomakehurst** [comment]
How about a compromise - add the list and delete endpoints in this change and defer multipart for a future PR?

**Comment by wojciechbulaty** [comment]
Hi @tomakehurst , I believe I have implemented what we have discussed. Let me know your thoughts.

**Pull request merged**
