### PR TITLE
Added hostname and systemValue helpers. See #1075

### PR DESCRIPTION
**Pull request by yuanpli**
Response Templating stub configured in docker image
```
{
    "request": {
        "urlPath": "/hostname",
        "method": "GET"
    },
    "response": {
        "body": "{{hostname}}",
        "transformers": ["response-template"]
    }
}
```
Container1 started with this image by
```docker run --hostname wiremock1 -d wiremock```
Container2 started with the same image by
```docker run --hostname wiremock2 -d wiremock```

When client requests http get /hostname on Container1 , it can get the response ***wiremock1***, and likewise, when requests on Container2, it can get the response ***wiremock2***.

### CODE REVIEW

**Comment by yuanpli** [comment]
Hi @tomakehurst Could you kindly pls review and approve the merge request? Hope it can be merged in next release. Thanks!

**Comment by yuanpli** [comment]
Hello, I am very sad that there is not any response from reviewers for a long time. Could anyone work on this merge request?

**Comment by yuanpli** [comment]
@tomakehurst 
Please review

**Comment by tomakehurst** [comment]
@yuanpli please stop nagging me. I'll review it when I have time to do so and have reviewed all the other stuff that arrived before it.

**Comment by tomakehurst** [comment]
This generally looks good, but I think there are a few things needed before I can merge it:

* Allowing unfiltered access to environment variables via templates is a security risk, since in many setups, environment variables are used for secrets. I suggest adding support for including only permitted variable names.
* Some acceptance tests. At a minimum: one showing resolution of hostname, a system property and an environment variable, and one showing that a forbidden env var cannot be accessed.

**Comment by tomakehurst** [comment]
I'd forgotten that #1085 is also trying to do more or less the same thing. Might be worth you joining forces?

**Comment by tomakehurst** [comment]
Interesting, I hadn't considered using the Java security manager for this.

A couple of issues I see with this:
1) I've no idea how or whether it'll work on Android. Do you have any idea whether Android implements the security manager in the same way as the JRE?
2) There's no easy way to specify which environment variables are permitted when running standalone from the command line.

Perhaps it'd be worth considering avoiding the security manager approach and just supporting a configuration option which is a list of regular expressions for names of permitted env vars?

**Comment by yuanpli** [comment]
> Interesting, I hadn't considered using the Java security manager for this.
> 
> A couple of issues I see with this:
> 
> 1. I've no idea how or whether it'll work on Android. Do you have any idea whether Android implements the security manager in the same way as the JRE?
> 2. There's no easy way to specify which environment variables are permitted when running standalone from the command line.
> 
> Perhaps it'd be worth considering avoiding the security manager approach and just supporting a configuration option which is a list of regular expressions for names of permitted env vars?

Hi, I didn't consider the Android environment.  Do you mean the configuration option should be regarded as one of the wiremock startup parameters?

**Comment by yuanpli** [comment]
BTW, if the configuration option and Response Templating stub both can be configured by user, it seems permission verification doesn't make any sense.

**Comment by tomakehurst** [comment]
WireMock's admin API doesn't have security by default, so without a means for the sysadmin to control which env vars are visible, an unauthenticated user could create a stub via the API that reveals sensitive variables via templating.

**Comment by yuanpli** [comment]
@tomakehurst Done the update. Pls have a review. Thanks!

**Pull request merged**
